# 1 
    SELECT * 
    FROM EMP 
    WHERE VL_COMI BETWEEN 500 AND 5000
    AND DT_ADMI > '01-01-2017';
# 2 
    SELECT COD_DEPT 
    FROM EMP 
    WHERE VL_COMI > 500;
# 3
    SELECT COD_DEPT, DSC_EMP
    FROM EMP;
# 4
    SELECT * 
    FROM EMP 
    WHERE COD_DEPT != 1 AND COD_DEPT != 3;
# 5 
    SELECT DSC_EMP, COD_EMP 
    FROM EMP
    WHERE COD_GERE != 10;
# 6  
    SELECT COD_EMP, DSC_EMP
    FROM EMP 
    ORDER BY DSC_EMP;
# 7
    SELECT DSC_EMP 
    FROM EMP 
    WHERE COD_GERE IS NULL;
# 8
    SELECT COD_DEP, DSC_DEP, ORCA_DEP
    FROM DEPT 
    ORDER BY ORCA_DEP DESC;
# 9 
    SELECT *
    FROM EMP
    WHERE DSC_EMP LIKE 'SILVA';
# 10
    SELECT D.COD_DEP, E.DSC_EMP
    FROM DEPT D
    JOIN EMP E
    ON D.COD_DEP = E.COD_DEPT
    ORDER BY COD_DEP;
